### ISSUE TITLE
Can't find pred_input_path and pred_output_path in DCiPatho_config.py 

### ISSUE THREAD

**Issue by Listen-Lii** [LorMeBioAI/DCiPatho#2]
Hi, I want to use this wonderful tool. 
However, there is no pred_input_path or pred_output_path in DCiPatho_config.py file. Can you fix this?

**Comment by Dx-wmc** [comment]
I encountered the same problem. When I wanted to modify the configuration file, I did not find these two parameters. Can you fix this bug?

**Comment by LorMeBioAI** [comment]
Thank you for your interest in using our tool! I apologize for the inconvenience caused by the missing pred_input_path and pred_output_path parameters in the DCiPatho_config.py file. I have fixed this bug, please see more details in readme.

**Comment by LorMeBioAI** [comment]
Thank you for your interest in using our tool! I apologize for the inconvenience caused by the missing pred_input_path and pred_output_path parameters in the DCiPatho_config.py file. I have fixed this bug, please see more details in readme.

**Comment by LorMeBioAI** [comment]
> Hi, I want to use this wonderful tool. However, there is no pred_input_path or pred_output_path in DCiPatho_config.py file. Can you fix this?

Thank you for your interest in using our tool! I apologize for the inconvenience caused by the missing pred_input_path and pred_output_path parameters in the DCiPatho_config.py file. I have fixed this bug, please see more details in readme.

**Comment by LorMeBioAI** [comment]
> Hi, I want to use this wonderful tool. However, there is no pred_input_path or pred_output_path in DCiPatho_config.py file. Can you fix this?

Thank you for your interest in using our tool! I apologize for the inconvenience caused by the missing pred_input_path and pred_output_path parameters in the DCiPatho_config.py file. I have fixed this bug, please see more details in readme.

**Comment by LorMeBioAI** [comment]
> I encountered the same problem. When I wanted to modify the configuration file, I did not find these two parameters. Can you fix this bug?
Thank you for your interest in using our tool! I apologize for the inconvenience caused by the missing pred_input_path and pred_output_path parameters in the DCiPatho_config.py file. I have fixed this bug, please redownload the code and see more details in readme.
